### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by w4nderlust** [searchivarius/nmslib#109]
Make the python bindings for Python 3

**Comment by searchivarius** [comment]
Thank you for the suggestion! We also appreciate people helping us with these kind of things.

**Comment by benfred** [comment]
Thanks for the amazing library - I've been playing with it for the last couple days and have been very impressed.

I made an initial attempt at bindings for NMSLIB  here https://github.com/benfred/nmsbind that supports both Python 2.7+ and 3.5+.

I'm using [pybind11](https://github.com/pybind/pybind11) to write this. Pybind11 radically simplifies writing bindings for C++ projects: it wraps the CPython API in a C++ interface, letting you avoid most of the boilerplate involved with writing Python extensions. For an example of how this looks, check out this file https://github.com/benfred/nmsbind/blob/master/nmsbind.cc .

The code here is mainly at the proof of concept stage - its missing several features from the bindings in NMSLIB (sparse vector support, string as object, multithreaded batch querying etc).

However,  this approach does have a couple advantages:
 * Works with Python2/3
 * Can be installed with pip (fixes #167)
 * There is CI running on travis (potentially addressing #62), testing python2.7 on linux and 3.6 on OSX
 * The API is more pythonic: doesn't need functions like nmslib.freeIndex to clear up memory (memory gets reclaimed when the python object is GC'ed instead)
 * There are docstrings for each method, and sensible default parameters
 * In theory should work on windows (though the windows CI server is complaining - so needs more work).

I realize this is a relatively big change - but I'd love to integrate this code into NMSLIB.
If you are interested in trying this approach, I will add the missing features that are currently present and get a pull request ready for you to review.

**Comment by searchivarius** [comment]
Hi @benfred thank you for the kind words, there are several of us :-)
Regarding your suggestions: this would be totally awesome if multithreading functionality can be, indeed, implemented.

**Comment by benfred** [comment]
Great! I'll work on putting this together - I don't think it will be too hard to get going.

I'm going to add the remaining missing features, and also make sure there is a layer for backwards compatibility so that existing tests will still work, and so that projects like https://github.com/erikbern/ann-benchmarks won't need updated.

**Comment by searchivarius** [comment]
@benfred this would be great. Great that you mentioned  ANN-benchmarks. @bileg currently works on extending them, so it will be great if you coordinate efforts.

**Comment by benfred** [comment]
I have a PR here https://github.com/searchivarius/nmslib/pull/195 .

I'm using openmp for the multithreaded knnQueryBatch code - it handles dynamic scheduling on the parallel for loop nicely (with the downside that its disabled on OSX): https://github.com/benfred/nmslib/blob/pybind/python_bindings/nmslib.cc#L124

I also added a compatibility layer here https://github.com/benfred/nmslib/blob/pybind/python_bindings/nmslib.cc#L566 so that existing python code should continue to work with the newer bindings.

For the ann-benchmarks, seems like they are referencing a previous version of the bindings:
https://github.com/erikbern/ann-benchmarks/blob/master/ann_benchmarks/main.py#L274
specifically the bindings are being imported as 'nmslib_vector' instead of nmslib - and it inits with a DataType.VECTOR instead of a DataType.DENSE_VECTOR . Tweaking the ann-benchmarks with those changes seems to make it work with this code.

I've also tested out the test_nmslib.py, sparse_bench.py and the previous unittests

**Comment by searchivarius** [comment]
Nice job @benfred many thanks! This worked fine for Python 2. However, I have troubles installing it for Python3 do you have any ideas why this might happen? Here is the build log:
```
sudo python3 setup.py install
running install
running bdist_egg
running egg_info
writing requirements to nmslib.egg-info/requires.txt
writing dependency_links to nmslib.egg-info/dependency_links.txt
writing top-level names to nmslib.egg-info/top_level.txt
writing nmslib.egg-info/PKG-INFO
reading manifest file 'nmslib.egg-info/SOURCES.txt'
writing manifest file 'nmslib.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c /tmp/tmp1by00kun.cpp -o tmp/tmp1by00kun.o -std=c++14
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.5m -c /tmp/tmpgqrx5pbg.cpp -o tmp/tmpgqrx5pbg.o -fvisibility=hidden
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
building 'nmslib' extension
creating build/temp.linux-x86_64-3.5
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../similarity_search/include -I/usr/local/include/python3.5 -I/home/leo/.local/include/python3.5m -I/usr/local/lib/python3.5/dist-packages/numpy/core/include -I/usr/include/python3.5m -c nmslib.cc -o build/temp.linux-x86_64-3.5/nmslib.o -O3 -fopenmp -DVERSION_INFO="1.6.1" -std=c++14 -fvisibility=hidden
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
In file included from /usr/local/include/python3.5/pybind11/pytypes.h:12:0,
                 from /usr/local/include/python3.5/pybind11/cast.h:13,
                 from /usr/local/include/python3.5/pybind11/attr.h:13,
                 from /usr/local/include/python3.5/pybind11/pybind11.h:36,
                 from nmslib.cc:18:
/usr/local/include/python3.5/pybind11/common.h:99:20: fatal error: Python.h: No such file or directory
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
```

**Comment by benfred** [comment]
Hmm - haven't seen that before. If you're on ubuntu maybe try something like 'sudo apt-get install python3-dev'

**Comment by searchivarius** [comment]
@benfred great that was necessary. In general, Python 3 installation seems to be a bigger pain-in-the-neck. For example, I had to do
```
python3 pip -m install ...
```
probably because python2 is default. Before doing this, one actually needs to install pip for Python3:
```
wget https://bootstrap.pypa.io/get-pip.py
python3 get-pip.py
```
Do you think it would be worth adding to README.me (I will update it)? Is there something else that I may miss?

**Comment by benfred** [comment]
It might be worth adding a note to the README - though when I installed python3 myself, apt-get automatically installed pip3 and the python3-dev packages.

**Comment by searchivarius** [comment]
Ohh, there's also pip3. This removes the concern, thank you!
