### ISSUE TITLE
Can you give me an advise of using which method

### ISSUE THREAD

**Issue by tangbohu** [searchivarius/nmslib#131]
Excuse me.  In my work, I have  two sets of data with one set is small while the other is large, and all datas are in the form <x,y>, where x \in R and y in R.
I need to retrieve each data in the small dataset  for its neighbours in the large dataset with the distance
measure d=abs( ||x_i-x_j|| - ||y_i -y_j|| ). All the building library and searching should be online. Can you give me an advise which algorithm in your library could handle this occasion.

**Comment by searchivarius** [comment]
Hi Nolan,

Is R actually R^n? One dimensional case isn't very challenging.

I also don't quite understand your distance metric description. Is it some
standard one?

Last, if you by "online" you mean that the index can be updated, then it's
not supported by API. Internally, many indices are built online, but to use
this, you need to hack the code.

---
Leo

**Comment by tangbohu** [comment]
Thank you very much for you reply. Actually x or y are R^3, denoting a point in the 3D space. 
X_i and X_j, Y_i and Y_j are two pair of corresponding points. In my research of 3D object recognition,
we denote d=abs( ||x_i-x_j|| - ||y_i -y_j|| ) as the isometric constraint, meaning that the distance between 
X_i and X_j with it of Y_i and Y_j should be similar. However, with a large set, it is still computational complex. I originally try to use landmark  multidimensional scaling to fast embed them into Euclidean space, but the distance is semi-metric. So I try to fast index then fast search.

**Comment by searchivarius** [comment]
Ohhh, I see you better write that your points are (x_1, x_2) and (y_1, y_2). 

I think you can sure use SW-graph, HNSW. It works fine with many semi-metrics including crazy ones like KL-div and Renyi-div You would need to implement your own space (which is quite simple).

What is more challenging though: you would need to use our C++ code directly, because functionality to add data points isn't directly exposed yet.
