### ISSUE TITLE
Memory leak in python binding

### ISSUE THREAD

**Issue by svirg** [searchivarius/nmslib#137]
Here is a snippet to reproduce:

~~~~
#!/usr/bin/python

import nmslib_vector
import numpy.random as npr
import resource

index = nmslib_vector.init('cosinesimil', [], 'hnsw',
                           nmslib_vector.DataType.VECTOR,
                           nmslib_vector.DistType.FLOAT)

dataset = [map(float, vect) for vect in npr.randn(1000, 8)]
for id, item in enumerate(dataset):
    nmslib_vector.addDataPoint(index, id, item)

nmslib_vector.createIndex(index, [])
nmslib_vector.setQueryTimeParams(index, [])

print resource.getrusage(resource.RUSAGE_SELF).ru_maxrss

for idx in xrange(10000):
    nn = nmslib_vector.knnQuery(index, 500, dataset[0])

print resource.getrusage(resource.RUSAGE_SELF).ru_maxrss
~~~~

The following patch solves the problem and the issue seems to be a HNSW method specific (due to dynamic allocation of `Object` that is never freed later on)
~~~~
diff --git a/python_vect_bindings/nmslib_vector.cc b/python_vect_bindings/nmslib_vector.cc
index 46af534..105607d 100644
--- a/python_vect_bindings/nmslib_vector.cc
+++ b/python_vect_bindings/nmslib_vector.cc
@@ -268,7 +268,7 @@ Py_BEGIN_ALLOW_THREADS
     res = knn.Result()->Clone();
     while (!res->Empty()) {
       ids.insert(ids.begin(), res->TopObject()->id());
-      res->Pop();
+      delete res->Pop();
     }
     delete res;
 Py_END_ALLOW_THREADS
~~~~

**Comment by searchivarius** [comment]
Hi @svirg thank you for the report. HNSW is still an experimental implementation.

That said, I think I know how to fix the memory leak issue. Your fix, unfortunately, will work only for HNSW. Other methods return pointers to existing objects, so that your fix will cause the same object to be deleted twice.

**Comment by yurymalkov** [comment]
@svirg great thanks for the fix! I think this can be helpful for those who use only HNSW in the nmslib. 

The issue also can be possibly fixed by adding the storing the list of nmslib "Object"s in the HNSW, and return the list entities instead of creating the new instance every time (this would not interfere with other nmslib methods, but require a little bit more memory). 

Alternatively, if you need only HNSW you can directly pass the ids from the HNSW without allocating "Object"'s (which is needed for keeping compatibility with nsmlib interface).

**Comment by searchivarius** [comment]
Hi @svirg could you check that the following fixes memory leak?
[fix137.zip](https://github.com/searchivarius/nmslib/files/582516/fix137.zip)

**Comment by svirg** [comment]
Yes, I confirm that it fixes the issue. Search results also look fine
I've tested it for both optimized and unoptimized indexes
