### ISSUE TITLE
Pip package

### ISSUE THREAD

**Issue by rw** [searchivarius/nmslib#167]
I'm excited to try out this library in Python. Would it be feasible to provide a pip install-able package? Annoy is exceptionally easy to use in this regard.

**Comment by searchivarius** [comment]
Yeah, we should do it some day (as well as Python 3 support). However, it will probably be after a few major changes.

**Comment by benfred** [comment]
So - with that last PR I *think* everything is set up properly to publish to pypi.  Its a pretty easy process, some details are here: http://peterdowns.com/posts/first-time-with-pypi.html . 

Basically there are just a couple things you need to do:

1) create an account on pypi: https://pypi.python.org/pypi?%3Aaction=register_form

2) Register nmslib with pypi (from nmslib/python_bindings folder):
 ```python setup.py register``` 

3) upload the code
 ```python setup.py sdist upload```

**Comment by searchivarius** [comment]
Great, I tried, but it seems to be a bit more complicated. I need a fresh head for this.
Thank for the help, this is greatly appreciated!

**Comment by searchivarius** [comment]
Ok, I have made a bit more progress. I uploaded the package to the test site, but I cannot re-install, @benfred would you care to try it on Linux: pip install -i https://testpypi.python.org/pypi -vvv nmslib
I am getting some weird errors:
```
  Could not find a version that satisfies the requirement nmslib (from versions: )
Cleaning up...
No matching distribution found for nmslib
Exception information:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.5/dist-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python3.5/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/local/lib/python3.5/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/local/lib/python3.5/dist-packages/pip/index.py", line 514, in find_requirement
    'No matching distribution found for %s' % req
pip.exceptions.DistributionNotFound: No matching distribution found for nmslib
```
I wonder if you have an idea regarding what's going on. 
Thank you!

**Comment by benfred** [comment]
I don't see the package on pypi, I would expect to see something here https://pypi.python.org/pypi/nmslib describing it. 

Do you have the output for  'python setup.py register' and 'python setup.py sdist upload' commands?

**Comment by searchivarius** [comment]
@benfred please, note that I currently play with test pip server
https://testpypi.python.org/pypi
Thank you!

**Comment by benfred** [comment]
Thanks! I realized right after posting =)

So I think what pip is doing is downloading the page from https://testpypi.python.org/simple/nmslib/ and checking to see what links match the system.  There are two python eggs there, but no wheels or source packages which I think might be the problem.

When I was writing the new bindings, I tested out a pip installable package - you can see different packages for each version: https://pypi.python.org/simple/nmsbind/ here .  I uploaded these with 'python setup.py sdist upload'  .  I think we need a sdist version here too (though precompiled wheels for linux aren't the worst idea).

**Comment by searchivarius** [comment]
Ohh, I see, it was recommended to use twine instead of sdist upload. I tried sdist upload and there are two issues:
1. We can upload for Python 2, Python 3 but not both versions.
2. An installation procedure tries to compile. This fails, b/c bindings come only with Python wrappers, but not NMSLIB sources.

**Comment by benfred** [comment]
I think the sdist package that gets uploaded will work with both python 2 + 3 - the problem is that we're missing the sources here.

I think the problem there is that I messed up the MANIFEST.in file :  I tried to include the nmslib with a relative directory - but those don't get included in the package =(.

I tried to fix here: https://github.com/searchivarius/nmslib/pull/197

**Comment by searchivarius** [comment]
Many thanks! It now works for Python3 (I mean pip3 install ...). However, not for Python2:
```
Collecting nmslib
  Using cached https://testpypi.python.org/packages/b3/5a/2cc32ca090e59219187f2a540576ba50e29f4a120f94a2cca6108c71bc27/nmslib-1.6.2.tar.gz
Collecting pybind11>=2.0 (from nmslib)
  Could not find a version that satisfies the requirement pybind11>=2.0 (from nmslib) (from versions: )
No matching distribution found for pybind11>=2.0 (from nmslib)
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
Another question would is related to additional packages that we don't build by default. But sometimes we want them for tests. Then, we do:
```
cmake -DWITH_EXTRAS=1
```
It also requires additional packages:
```
libboost-all-dev libgsl0-dev libeigen3-dev
```
I hope I am not too annoying, but we need FALCONN and LSHKIT in ann-benchmark.

**Comment by benfred** [comment]
Awesome! Glad its starting to come together.

For the python2 version - I think the error might be because pybind11 ins't registered with testpypi index  (like https://testpypi.python.org/pybind11/ returns a 404, vs https://pypi.python.org/pybind11/ which doesn't).  Installing pybind11 direct from pypi (pip install pybind11) should resolve, and I don't think this error will happen once you push nmslib to the production pypi. At least this successfully installed here on my mac using python2:

```
Bens-MacBook-Pro-2:~ ben$ pip install -i https://testpypi.python.org/pypi nmslib
Collecting nmslib
  Downloading https://testpypi.python.org/packages/b3/5a/2cc32ca090e59219187f2a540576ba50e29f4a120f94a2cca6108c71bc27/nmslib-1.6.2.tar.gz (351kB)
    100% |████████████████████████████████| 358kB 1.6MB/s 
Requirement already satisfied: pybind11>=2.0 in ./anaconda2/lib/python2.7/site-packages (from nmslib)
Requirement already satisfied: numpy in ./anaconda2/lib/python2.7/site-packages (from nmslib)
Building wheels for collected packages: nmslib
  Running setup.py bdist_wheel for nmslib ... done
  Stored in directory: /Users/ben/Library/Caches/pip/wheels/c2/34/91/1445fe84da33524dcbc6ffe6abd99372008aeb6f818e5ca8be
Successfully built nmslib
Installing collected packages: nmslib
Successfully installed nmslib-1.6.2
```

For installing the extras - I left the existing logic in place, so it shouldn't be any harder than whats in master. If you build the extras with cmake first, running 'python setup.py install' should pick up the prebuilt liblshkit.a and libNonMetricSpaceLib.a files: https://github.com/searchivarius/nmslib/blob/develop/python_bindings/setup.py#L32 . I haven't tested the liblshkit.a integration, but I think this should work. The only time setup.py will build all the nmslib source is if those files don't exist.

I couldn't see any good way of doing this from the package thats installed from pypi : cmake does a good job of detecting boost/eigen and there isn't any obvious/easy way of replicating in python

**Comment by searchivarius** [comment]
1. You seem to be right, I am installing it now from the main web site.
2. Regarding extras: I didn't realize that. Indeed, for pypi we only want to ship the core library, which will, in fact, be much smaller in the future. For anything else, we can use the old procedure : 
```
wget <release files>
cd ...
cmake -D WITH_EXTRAS=1
python setup.py install --user
```
Overall, @benfred this was an awesome job, which will greatly help people to use the library. Many thanks!
