### ISSUE TITLE
HNSW - one step is omitted for insertion. 

### ISSUE THREAD

**Issue by kwangswei** [searchivarius/nmslib#170]
When add the new element, we need to update the endpoints to the closest elements from friends list.
(line number 11 of algorithm 1 on page 6 in the paper - "Efficient and robust approximate nearest neighbor search using Hierarchical Navigable Small World graphs")

But in the Hnsw<dist_t>::add() function, there is no this process in the loop. (line number 520 of hnsw.cc). It doesn't change the "ep" pointer.

Please review this issue.

**Comment by searchivarius** [comment]
Thank you for comparing code with the manuscript! I have also looked at both and it seems that you are correct. The enterPoint (not endPoint I believe) is not updated in the second loop or so it seems to be. I tried to fix this:
```
             while (!resultSet.empty()) {
                 ep = resultSet.top().getMSWNodeHier(); // memorizing the closest
                 link(resultSet.top().getMSWNodeHier(), NewElement, level, space, delaunay_type_);
                 resultSet.pop();
             }
```
and test on SIFT, but this didn't change results much. In fact, results slightly deteriorated (though this might be random). I hope @yurymalkov could provide more comments. But, indeed, there seems to be a mismatch between the code and the pseudo-code in the paper.

**Comment by yurymalkov** [comment]
@kwangswei Thanks for the comment!
@searchivarius It affects only a fraction of element insertions which have level>0. I would expect there will be some notable difference in index time for huge low dimensional or clustered datasets (such as wiki8) with little effect on the accuracy.

**Comment by searchivarius** [comment]
@yurymalkov thanks for clarifying. Do you think the above-mentioned fix is
1) correct
2) can potentially reduce indexing time?
BTW, Why do you think it will little effect on high-dimensional sparse data? I guess finding nearest neighbors in lower level should be faster if you start from a better point?

**Comment by yurymalkov** [comment]
@searchivarius 
1. It seems that the fix is correct. Maybe we should also rewrite the fragment to pass several closest elements instead of just one, it should also help. However tests are needed to check that it has only positive effect.
2. It think yes.
My intuition is: firstly, for high dimensional datasets higher M is usually better for performance. And the fraction of affected elements is roughly 1/M, so the effect decreases for higher dimensionality data. Secondly, in general, performance on low dimensional and clustered data much more heavily relies on the layered structure (which is this case is corrupted).

**Comment by searchivarius** [comment]
Hi @kwangswei and @yurymalkov I eventually have implemented a fix: it doesn't make things worse and I can close this issue.
